server:
  port: 8081
  servlet:
    context-path: /whisper
app:
  dbconfig:
    - {user: test1, password: pwd001, dbname: updateDb}
    - {user: test2, password: pwd002, dbname: viewdb}
  appName: テストAPP
  version: V1.0
